In this guide, you are going to consume the https://bintray.com/docs/api/[Bintray API] from a Micronaut application.

In particular, we consume the https://bintray.com/docs/api/#_get_packages[Get Packages] endpoint.

____
Get a list of packages in the specified repository, optionally specify a starting position and/or a name prefix filter.
____

This API resource can be consumed by both authenticated and anonymous clients.

Initially, you will consume it anonymously, later we will discuss authentication.

Modify `src/main/resources/application.yml` to create some configuration parameters.

[source,java]
.src/main/resources/application.yml
----
include::{sourceDir}/src/main/resources/application.yml[tag=bintrayconfig]
----

To encapsulate type-safe configuration retrieval, we use a https://docs.micronaut.io/latest/guide/index.html#configurationProperties[`@ConfigurationProperties`] object:

[source,java]
.src/main/java/example/micronaut/BintrayConfiguration.java
----
include::{sourceDir}/src/main/java/example/micronaut/BintrayConfiguration.java[]
----

In this guide, you are going to fetch https://bintray.com/micronaut/profiles[Micronaut profiles packages]. Those packages are used by the https://docs.micronaut.io/latest/guide/index.html#cli[Micronaut CLI].

To consume the Bintray API, you will use Micronaut HTTP Client.
