Create a Controller. It uses both (low-level and declarative clients). It showcases several Micronaut's capabilities.

* Micronaut supports any framework that implements Reactive Streams, including RxJava, and Reactor. Thus, you can easily and efficiently
compose multiple HTTP client calls without blocking (which will limit the throughput and scalability of your application).
* Micronaut enables you to consume/produce https://docs.micronaut.io/snapshot/guide/index.html#clientStreaming[JSON Streams].


[source,java]
.src/main/java/example/micronaut/BintrayController.java
----
include::{sourceDir}/src/main/java/example/micronaut/BintrayController.java[]
----

<1> The class is defined as a controller with the http://docs.micronaut.io/snapshot/api/io/micronaut/http/annotation/Controller.html[@Controller] annotation mapped to the path `/bintray`
<2> Inject beans via constructor injection.
<3> The http://docs.micronaut.io/snapshot/api/io/micronaut/http/annotation/Get.html[@Get] annotation is used to map the index method to all requests that use an HTTP GET
<4> The `packagesWithLowLevelClient` returns a Maybe which may or may not emit an item. If an item is not emitted a 404 is returned.
<5> In order to do JSON streaming you can declare a controller method that returns a `application/x-json-stream` of JSON objects.
<6> You can return reactive types, such as an RxJava `Flowable`.

