include::{commondir}/common-spockinjavaapp.adoc[]

Create a test which verifies both clients work as expected and the controller echoes the output of the Bintray API in a Reactive way.

[source,groovy]
.src/test/groovy/example/micronaut/BintrayControllerSpec.groovy
----
include::{sourceDir}/src/test/groovy/example/micronaut/BintrayControllerSpec.groovy[]
----

<1> The AutoCleanup extension makes sure the `close()` method of an object (e.g. `EmbeddedServer`) is called each time a feature method is finished
<2> To run the application from a unit test you can use the http://docs.micronaut.io/api/io/micronaut/runtime/server/EmbeddedServer.html[EmbeddedServer] interface
<3> Register a `RxClient` bean in the application context and point it to the embedded server URL. The `EmbeddedServer` interface provides the URL of the server under test which runs on a random port.
<4> Micronaut makes it easy to parse JSON into Java objects.
<5> Use `status` to check the HTTP status code.
<6> Use `.body()` to retrieve the parsed payload.


