include::{commondir}/common-spockinjavaapp.adoc[]

Create a test which verifies both clients work as expected and the controller echoes the output of the Bintray API in a Reactive way.

[source,groovy]
.src/test/groovy/example/micronaut/BintrayControllerSpec.groovy
----
include::{sourceDir}/src/test/groovy/example/micronaut/BintrayControllerSpec.groovy[]
----

<1> The AutoCleanup extension makes sure the `close()` method of an object (e.g. `EmbeddedServer`) is called each time a feature method is finished
<2> To run the application from a unit test you can use the http://docs.micronaut.io/api/io/micronaut/runtime/server/EmbeddedServer.html[EmbeddedServer] interface
<3> Micronaut’s HTTP client includes support for streaming data over HTTP via the https://docs.micronaut.io/snapshot/api/io/micronaut/http/client/RxStreamingHttpClient.html[RxStreamingHttpClient]. Register a `RxStreamingHttpClient` bean in the application context and point it to the embedded server URL. The `EmbeddedServer` interface provides the URL of the server under test which runs on a random port.
<4> Sometimes, receiving just the object is not enough and you need information about the response. In this case, instead of `retrieve` you should use the `exchange` method.
<5> Micronaut makes it easy to parse JSON into Java objects.
<6> Use `status` to check the HTTP status code.
<7> Use `.body()` to retrieve the parsed payload.
<8> Use the `jsonStream` method, which returns a `Flowable`, to consume the endpoint which generates a JSON Stream.


