Create a test which verifies both clients work as expected and the controller echoes the output of the Bintray API in a Reactive way.

[source,java]
.src/test/java/example/micronaut/BintrayControllerTest.java
----
include::{sourceDir}/src/test/java/example/micronaut/BintrayControllerTest.java[]
----

<1> Annotate the class with `@MicronatTest` to let Micronaut starts the embedded server and inject the beans. More info: https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html[https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html].
<2> Inject the `RxStreamingHttpClient` bean in the application context.
<3> Sometimes, receiving just the object is not enough and you need information about the response. In this case, instead of `retrieve` you should use the `exchange` method.
<4> Micronaut makes it easy to parse JSON into Java objects.
<5> Use `status` to check the HTTP status code.
<6> Use `.body()` to retrieve the parsed payload.
<7> Use the `jsonStream` method, which returns a `Flowable`, to consume the endpoint which generates a JSON Stream.
